version: 2.1
orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@2.5.0
  slack: circleci/slack@4.12.6
workflows:
  test-build-publish-and-notify:
    jobs:
      - test
      - docker/publish:
          image: lazron/scaffnode
          requires:
            - test
      - notify:
          context: slack-secrets
          requires:
            - docker/publish
jobs:
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          template: success_tagged_deploy_1
          mentions: "@channel"
          event: pass
      - slack/notify:
          event: fail
          mentions: "@channel"
          template: basic_fail_1
  test:
    executor:
      name: node/default
      tag: "16"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
