version: 2.1
orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@2.5.0
  slack: circleci/slack@4.12.6
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: lazron/scaffnode
