version: 2.1
orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@2.5.0
  slack: circleci/slack@4.12.6
workflows:
  build-publish-and-notify:
    jobs:
      - docker/publish:
          image: lazron/scaffnode
      - notify:
          context: slack-secrets
          requires:
            - docker/publish
jobs:
  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          template: success_tagged_deploy_1
          mentions: '@channel'
          event: pass
